In [1]:
import numpy as np

In [6]:
'''1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array. Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]'''
lista = [12.23, 13.32, 100, 36.32]
np.array(lista)

array([  12.23,   13.32,  100.  ,   36.32])

In [15]:
'''2. Write a Python program to create a null vector of size 10 and update sixth value to 11.'''
a = np.repeat(np.nan,10)
a[5] = 11

array([ nan,  nan,  nan,  nan,  nan,  11.,  nan,  nan,  nan,  nan])

In [18]:
'''3. Write a Python program to create a array with values ranging from 12 to 38.'''
np.arange(12,39)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [29]:
'''4. Write a Python program to reverse an array (first element becomes last).'''
b = np.arange(10)
b[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [60]:
'''5. Write a Python program to create a 2d array with 1 on the border and 0 inside.Expected
Output: Original array: [[ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1.
1. 1. 1. 1.]] 1 on the border and 0 inside in the array [[ 1. 1. 1. 1. 1.] [ 1. 0. 0. 0. 1.] [ 1.
0. 0. 0. 1.] [ 1. 0. 0. 0. 1.] [ 1. 1. 1. 1. 1.]]'''

c = np.ones((4,4))
c[1:-1,1:-1] = 0
c

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [65]:
'''6. Write a Python program to add a border (filled with 0’s) around an existing array'''
np.pad(c,pad_width=1,mode='constant')

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [92]:
'''7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern
Checkerboard pattern: [[0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1
0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0]] hint: Explore the
use of x[a :: b, :: c] = d, x[:: e, f :: g] = h, where the letters are integer numbers.'''

b = np.ones((8,8))
b[0::2,::2] = 0
b[1::2,1::2] = 0
b


array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

In [105]:
'''8. Write a Python program to convert the values of Centigrade degrees into Fahrenheit
degrees. Centigrade values are stored into a NumPy array.
Sample Array [0, 12, 45.21 ,34, 99.91]
Expected Output:
Values in Fahrenheit degrees: [0.0 12.0 45.21 34.0 99.91]
Values in Centigrade degrees: [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778].
Use functions and list comprehension read the link https: // www. pythonforbeginners.
com/ lists/ list-comprehensions-in-python/ , to additional information about of
list comprehension in python.'''

e = [0, 12, 45.21 ,34, 99.91]


[((i-32)*5/9) for i in e]

[-17.77777777777778,
 -11.11111111111111,
 7.33888888888889,
 1.1111111111111112,
 37.727777777777774]

In [107]:
'''9. Write a Python program to find the set difference of two arrays. The set difference will
return the sorted, unique values in array1 that are not in array2. Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays: [ 0 20 60 80]
Hint:explore the use of function np.setdiff1d.'''

Array1= [ 0, 10, 20, 40, 60, 80]
Array2= [10, 30, 40, 50, 70, 90]

[i for i in Array1 if i not in Array2]

[0, 20, 60, 80]

In [113]:
'''10. Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0’s
elsewhere.'''

np.diag([4,5,6,7,8])

array([[4, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 6, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 8]])