In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [35]:
#1
list=[1,2,3,4,5,6,7,8,9,10]


In [7]:
list


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
nplist=np.array(list)
nplist

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
print (nplist)

[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
#2
v1=np.repeat(np.nan,10)


In [22]:
print(v1)

[nan nan nan nan nan nan nan nan nan nan]


In [24]:
v1[5]=11

In [25]:
print(v1)

[nan nan nan nan nan 11. nan nan nan nan]


In [31]:
#3
rango=np.arange(12,39)
rango

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [38]:
#4
rango[::-1]

array([38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

In [11]:
#5
a = np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [21]:
#6
borde = np.ones((3,3))
print(borde)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
borde= np.pad(borde, pad_width=1, mode='constant', constant_values=0)
print(borde)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
#7
chb= np.zeros((8,8),dtype=int)
print(chb)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [26]:
chb[1::2,::2] = 1
chb[::2,1::2] = 1
print(chb)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
#8 centigrades into farenheit
#°C  x  9/5 + 32 = °F
#(°F  -  32)  x  5/9 = °C

In [30]:
f=[0.0, 12.0, 45.21, 34.0, 99.91]
print(f)

[0.0, 12.0, 45.21, 34.0, 99.91]


In [33]:
[i for i in f]

[0.0, 12.0, 45.21, 34.0, 99.91]

In [35]:
c=[((i-32)*(5/9)) for i in f]
c

[-17.77777777777778,
 -11.11111111111111,
 7.3388888888888895,
 1.1111111111111112,
 37.727777777777774]

In [39]:
#9 set difference between two arrays
# hint: np.setdiff1d
a1=[0,10,20,40,60,80]
a2=[10,30,40,50,70,90]
dif=np.setdiff1d(a1,a2)
dif

array([ 0, 20, 60, 80])

In [44]:
 #10 CREATE 2D ARRAY WHOSE DIAGONAL 4,5,6 ELSEWHERE 0´S
Z=np.diag([4,5,6,8])
print(Z)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
